GET http://localhost:3000
####
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "your_username",
  "password": "your_password"
}
####
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "your_username",
  "password": "your_password"
}
####
GET http://localhost:3000/ignore/mails/AQMkADAwATYwMAItYTY4Ni00N2Y1LTAwAi0wMAoARgAAAyw-ofQyEi5Bklxj1g8u_Y4HAN-1MHQRJFtFgbxVLR0XmRAAAAIBDAAAAKgFPS6eKelFh-Gpddn9_Q0ABmFtAMMAAAA=
###
GET http://localhost:3000/ignore/mailboxes/00000000-0000-0000-a926-8f0c31275153
####
GET http://localhost:3000/ignore/mails
###
GET http://localhost:3000/ignore/users/qwe
###
GET http://localhost:3000/mails?page=0&size=10